print(int("3.5"))  # '3,5'は整数に変換することはできないので、例外のvalueErrorとなる。
